### ISSUE TITLE
Test fails with the latest localstack image

### ISSUE THREAD

**Issue by haykbaluyan** [aquasecurity/go-mock-aws#1]
Looks like tests are failing with latest localstack image (`localstack/localstack:latest`). The same tests succeed with `localstack/localstack:1.4`

Test case - [Test_SQSQueueEncrypted in internal/adapters/cloud/aws/sqs/sqs_test.go](https://github.com/averlon-security/defsec/blob/master/internal/adapters/cloud/aws/sqs/sqs_test.go#L30)

The culprit seem to be that, [initComplete](https://github.com/aquasecurity/go-mock-aws/blob/99847deb62b0d46dd65cc6cc38174bce9b7a5971/localstack.go#L153) method returns `false` infinitely because it always retrieves the first log message.

**Comment by haykbaluyan** [comment]
looks like the below change is what caused the break. `docker-entrypoint-initaws.d` no longer is viable mount point.

https://github.com/localstack/localstack/commit/29010654a86a307e790f6ebb9754ebbca3601637

Official defsec CI build was not broken yet most likely because it is used cached localstack latest image.

**Comment by simar7** [comment]
yes we're aware of it, defsec CI was broken as a result. we will pin it to version 1.4 for the timebeing.
